besu --data-path=../node2/data \
     --revert-reason-enabled \
     --p2p-port=30302 \
     --genesis-file=../genesis.json \
     --rpc-http-enabled \
     --rpc-http-api=ETH,NET,QBFT \
     --host-allowlist="*" \
     --rpc-http-cors-origins="all" \
     --rpc-http-port=8082 \
     --rpc-ws-enabled \
     --rpc-ws-port=7072 \
     --min-gas-price=0